import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getDictionary } from "@/app/[lang]/dictionaries";
import { BackToTopButton } from "@/components/back-top-top-button";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { GridBackground } from "@/components/ui/grid-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    lang: "en" | "es";
  }>;
}>) {
  const { lang } = await params;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang} suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GridBackground />
        <div className="max-w-5xl mx-auto flex flex-col min-h-screen w-full z-10 relative px-6">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="flex-1">
              <div className="py-6">
                <Header dict={dict.header} />
                {children}
              </div>
              <Footer dict={dict.footer} />
            </div>
          </ThemeProvider>
        </div>
        <BackToTopButton />
      </body>
    </html>
  );
}
